# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e5fe068fa22d79525156a4a5aebccda7bbd96b1485cba72253ebfd943105c53d8bbc0f6aac6781605d6ad4652f44e3c3aeeebdfedbdf11d8e34747bbfeb832

test:
  secret_key_base: 088089048180e5701685157cd2729fd8f42fc77612804fed622605cc5b6b7cef72c9662460e87a8112dc799951fdab7ded19a22184989c16922d92292517acf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
